(import auth)
(import https)

(defn check [value message]
  (unless value (error message)))

(defn main [& args]
  (case (get args 1)
    "https" (do
              (def started (os/time))
              (var heartbeat nil)
              (ev/go (fn [] (ev/sleep 0.05) (set heartbeat (os/time))))
              (def result (protect (https/get (args 2) (args 3))))
              (check (= (= "ok" (args 4)) (first result)) "HTTPS outcome mismatch")
              (when (string/has-suffix? "/slow" (args 2))
                (check (and heartbeat (< (- heartbeat started) 1)) "HTTPS must not block the event loop"))
              (when (first result) (check (= "trusted keys" (result 1)) "HTTPS response mismatch")))
    "cache" (do
              (def directory (args 2))
              (def now @[(os/time)])
              (var calls 0)
              (var source "old.json")
              (def context (auth/context "https://test.cloudflareaccess.com" "sqlite-viewer"
                                         (fn [] (++ calls) (string (slurp (string directory "/" source))))
                                         (fn [] (now 0))))
              (def old (string (slurp (string directory "/old.jwt"))))
              (def new (string (slurp (string directory "/new.jwt"))))
              (check (auth/verify context old) "initial keys verify")
              (check (= calls 1) "cached verification avoids fetch")
              (set source "rotated.json")
              (check (not (first (protect (auth/verify context new)))) "unknown key denied during cooldown")
              (check (= calls 1) "unknown key fetch throttled")
              (put now 0 (+ (now 0) 61))
              (check (auth/verify context new) "unknown key triggers rotation refresh")
              (check (= calls 2) "rotation fetched once")
              (check (auth/verify context old) "overlapping old key remains valid")
              (set source "invalid.json")
              (put now 0 (+ (now 0) 3601))
              (check (auth/verify context new) "invalid refresh retains cached verifier")
              (check (= calls 3) "hourly refresh attempted")
              (check (not (first (protect (auth/verify context "invalid")))) "invalid token rejected")
              (check (= calls 3) "failure cooldown prevents repeated fetch")
              (put now 0 (+ (now 0) 86400))
              (check (not (first (protect (auth/verify context new)))) "expired key cache denies access")
              (set source "rotated.json")
              (put now 0 (+ (now 0) 61))
              (check (auth/verify context new) "cache recovers after outage"))
    (error "Unknown test mode"))
  (print "Auth/client checks passed"))
