(import sqlite3 :as sql)
(import db)
(import watch)
(import ui)
(import auth)
(import query)
(def checks @[0])

(defn check [value message]
  (unless value (error (string "FAIL: " message)))
  (put checks 0 (inc (checks 0))))
(defn main [&]
  (def conn (sql/open ":memory:"))
  (sql/eval conn "CREATE TABLE items(id INTEGER PRIMARY KEY, name TEXT, note TEXT)")
  (def state (watch/attach conn))
  (watch/eval! state "INSERT INTO items VALUES(1,'Ada',NULL)")
  (check (= 1 (state :version)) "committed insert invalidates")
  (watch/eval! state "BEGIN")
  (watch/eval! state "UPDATE items SET name='uncommitted'")
  (check (= 1 (state :version)) "uncommitted update is invisible")
  (watch/eval! state "ROLLBACK")
  (check (= 1 (state :version)) "rollback does not publish")
  (watch/eval! state "BEGIN")
  (watch/eval! state "UPDATE items SET name='Grace'")
  (watch/eval! state "COMMIT")
  (check (= 2 (state :version)) "explicit transaction publishes after commit")
  (watch/eval! state "CREATE TABLE compact(id TEXT PRIMARY KEY) WITHOUT ROWID")
  (watch/eval! state "INSERT INTO compact VALUES('one')")
  (check (= 4 (state :version)) "commit fallback covers WITHOUT ROWID and DDL")
  (watch/eval! state "DELETE FROM items")
  (check (= 5 (state :version)) "truncate optimization invalidates")
  (watch/eval! state "INSERT INTO items VALUES(1,'Grace',NULL),(2,'Ada','<script>alert(1)</script>')")
  (check (not (first (protect (watch/eval! state "INSERT INTO items VALUES(3,'No',NULL); DELETE FROM items")))) "tracked eval rejects multiple statements before mutation")
  (def database @{:db conn})
  (check (= (db/quote-id "a\"b") "\"a\"\"b\"") "identifier quoting")
  (def s (db/state database {"table" "items" "search" "ada"}))
  (def rows (db/data database s))
  (check (= 1 (rows :total)) "parameterized search")
  (check (= "Ada" (((rows :rows) 0) 1)) "search selects correct row")
  (check (not (first (protect (db/state database {"table" "items; DROP TABLE items"})))) "unknown table rejected")
  (check (not (first (protect (db/state database {"table" "items" "sort" "random()"})))) "unknown sort rejected")
  (sql/eval conn "CREATE TABLE \"odd.table\"(\"a\"\"b\" TEXT)")
  (sql/eval conn "INSERT INTO \"odd.table\" VALUES(?)" ["literal ' OR 1=1;--"])
  (def odd-state (db/state database {"table" "odd.table" "search" "' OR 1=1;--"}))
  (check (= 1 ((db/data database odd-state) :total)) "expression query quotes literal dots and double quotes")
  (def filtered (db/state database {"table" "items" "filter" "name" "value" "ad" "op" "contains"}))
  (check (= "Ada" (get-in (db/data database filtered) [:rows 0 1])) "expression contains filter")
  (def exact (db/state database {"table" "items" "filter" "name" "value" "Ada"}))
  (check (= 1 ((db/data database exact) :total)) "expression equals filter")
  (check (= 0 ((db/data database (db/state database {"table" "items" "search" "' OR 1=1;--"})) :total))
         "search input stays a bound value")
  (check (= "<span title=\"&lt;script&gt;&amp;&quot;&#x27;\">&lt;script&gt;&amp;&quot;&#x27;</span>"
            (ui/render (ui/cell "<script>&\"'"))) "cell text and attributes are escaped once")
  (check (string/find " selected=\"\"" (ui/render (ui/option "x" "x"))) "selected option")
  (check (= "<option value=\"x\">x</option>" (ui/render (ui/option "x" "y"))) "unselected option omits boolean attribute")
  (check (= "<div><span>first</span>after<span>last</span></div>"
            (ui/render [:div [:span "first"] "after" nil [:span "last"]])) "mixed children and optional markup")
  (check (string/find "&lt;script&gt;" (ui/render (ui/grid rows))) "grid escapes database content")
  (check (string/find "&lt;script&gt;" (ui/render (ui/error-result "<script>"))) "error message escaping")
  (check (= "Grace" (get-in (query/run conn "SELECT name FROM items WHERE id=?" [1]) [:rows 0 0])) "safe query binds parameters")
  (each statement ["DELETE FROM items" "ATTACH '/tmp/no.db' AS other" "PRAGMA writable_schema=ON"
                   "SELECT 1; SELECT 2" "SELECT load_extension('anything')" "VACUUM INTO '/tmp/no.db'"
                   "CREATE TABLE nope(x)" "UPDATE items SET name='bad' RETURNING *"]
    (check (not (first (protect (query/run conn statement [])))) (string "reject " statement)))
  (check (= "9223372036854775807" (get-in (query/run conn "SELECT 9223372036854775807") [:rows 0 0])) "int64 precision")
  (check (= 2 (length ((query/run conn "SELECT * FROM items") :rows))) "guard failure leaves connection usable")
  (check (not (first (protect (query/run conn "WITH RECURSIVE n(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM n) SELECT sum(x) FROM n")))) "recursive query budget")
  (check (= "2" (get-in (query/run conn "SELECT count(*) FROM items") [:rows 0 0])) "interrupted statement cleaned up")
  (check (auth/permits? {"databases" @["Studio"]} "Studio") "database grant")
  (check (not (auth/permits? {"databases" @["Other"]} "Studio")) "database denial")
  (check (= "abc" (auth/token {:headers {"cookie" "other=x; sv_session=abc; extra=z"}})) "session cookie extraction")
  (watch/detach state)
  (sql/close conn)
  (print "Passed " (checks 0) " core checks"))
